# Generated by Django 2.2 on 2022-01-06 11:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('saiapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Teacher',
            fields=[
                ('TeacherID', models.IntegerField(default=0, editable=False, primary_key=True, serialize=False, verbose_name='ID')),
                ('TeacherName', models.CharField(max_length=100, verbose_name='Name')),
                ('TeacherEmail', models.EmailField(max_length=254, verbose_name='E-Mail')),
                ('TeacherPhone', models.IntegerField(serialize=False, verbose_name='Phone Number')),
                ('TeacherLocation', models.CharField(max_length=100, verbose_name='Location')),
                ('TeacherStatus', models.CharField(choices=[('A', 'Active'), ('I', 'Inactive')], max_length=10, verbose_name='Status')),
            ],
        ),
    ]
