# Generated by Django 2.2 on 2022-02-15 13:14

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('saiapp', '0003_parayangroup'),
    ]

    operations = [
        migrations.CreateModel(
            name='Location',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('locname', models.CharField(max_length=100, verbose_name='Location Name')),
            ],
        ),
        migrations.CreateModel(
            name='Registrationdetails',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('TeacherName', models.CharField(max_length=100, verbose_name='Name')),
                ('TeacherEmail', models.EmailField(max_length=100, verbose_name='E-Mail')),
                ('TeacherPhone', models.IntegerField(verbose_name='Phone Number')),
                ('TeacherLocation', models.CharField(max_length=100, verbose_name='Location')),
                ('GroupID', models.CharField(max_length=50, verbose_name='Parayan Group ID')),
                ('GroupName', models.CharField(max_length=100, verbose_name='Parayan Group Name')),
            ],
        ),
        migrations.AlterField(
            model_name='parayangroup',
            name='GrpID',
            field=models.CharField(max_length=20, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='parayangroup',
            name='GrpTeacher',
            field=models.ForeignKey(limit_choices_to={'TeacherStatus': 'A'}, on_delete=django.db.models.deletion.PROTECT, to='saiapp.Teacher'),
        ),
        migrations.AlterField(
            model_name='teacher',
            name='TeacherID',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, unique=True, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='teacher',
            name='TeacherStatus',
            field=models.CharField(choices=[('A', 'Active'), ('I', 'Inactive')], default='Active', max_length=10, verbose_name='Status'),
        ),
        migrations.CreateModel(
            name='volunteer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('volName', models.CharField(max_length=100, verbose_name='Name')),
                ('language', models.CharField(max_length=25, verbose_name='Language')),
                ('phonenumber', models.IntegerField(serialize=False, verbose_name='Phone Number')),
                ('email', models.EmailField(max_length=254, verbose_name='E-Mail')),
                ('createddate', models.DateField(auto_now=True, verbose_name='Created Date')),
                ('location', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='saiapp.Location')),
            ],
            options={
                'db_table': 'volunteer',
            },
        ),
        migrations.CreateModel(
            name='devotee',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('DevName', models.CharField(max_length=100, verbose_name='Name')),
                ('Devconname', models.CharField(max_length=100, verbose_name='Contact Name')),
                ('RollNumber', models.IntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(48)], verbose_name='Roll No.')),
                ('Language', models.CharField(max_length=25, verbose_name='Language')),
                ('House', models.CharField(choices=[('Red', 'Red'), ('Yellow', 'Yellow'), ('Blue', 'Blue'), ('Green', 'Green')], default='Red', max_length=10, verbose_name='House')),
                ('Status', models.SmallIntegerField()),
                ('phonenumber', models.IntegerField(serialize=False, verbose_name='Phone Number')),
                ('email', models.EmailField(max_length=254, verbose_name='E-Mail')),
                ('createddate', models.DateField(auto_now=True, verbose_name='Created Date')),
                ('GrpID', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='saiapp.ParayanGroup', verbose_name='Parayan Group')),
                ('Location', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='saiapp.Location')),
            ],
            options={
                'db_table': 'devotee',
            },
        ),
    ]
