# Generated by Django 2.2 on 2022-02-15 13:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('saiapp', '0004_auto_20220215_1844'),
    ]

    operations = [
        migrations.AlterField(
            model_name='teacher',
            name='TeacherLocation',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='saiapp.Location', verbose_name='Location'),
        ),
    ]
