# Generated by Django 2.2 on 2022-03-13 18:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('saiapp', '0007_auto_20220311_1652'),
    ]

    operations = [
        migrations.AlterField(
            model_name='devotee',
            name='Status',
            field=models.CharField(choices=[('A', 'Active'), ('I', 'Inactive')], default='Active', max_length=10, verbose_name='Status'),
        ),
    ]
